### ISSUE TITLE
Pie Chart Issue

### ISSUE THREAD

**Issue by AbbottF** [IgniteUI/app-builder#19]
During todays Webinar, I dropped a pie chart on the right hand column. As soon as i clicked the DATA button, the chart got smaller and moved to the top of the column and several "shadow" charts appeared below it. This was the same with the latest desktop download and the web version.
![AppBuilderChartIssue](https://user-images.githubusercontent.com/229561/192583456-145fde56-ee68-44a2-a790-106b19eda0ae.png)

**Comment by zdrawku** [comment]
Hey @AbbottF, I guess you already answered your question as it was from some time ago - Mode "Data" is part of the Repeat section and actually allows you to repeat the component/element through data collection. This is useful when the component is:
- Declarative, for example, Tree component or Select component. Both of them have Items/Children that can be defined and bound by repeating through a collection.
- Or you want to bind a Visual component to an Array of Object (for example Card component) in order to show more information per Data Item from the collection.

The property that handles the component data binding is called Data and it is under the Component X properties.

**Comment by AbbottF** [comment]
Thanks
