### ISSUE TITLE
Indigo.design - Dialog window navigation did not work.

### ISSUE THREAD

**Issue by jennifershih** [IgniteUI/app-builder#7]
I set up Dialog window, when I click logout, I expect it navigate to loginPage/login.
After code generation, when I run project, logout button didn't work.

![1 screenshot-indigo design](https://user-images.githubusercontent.com/17427142/141880537-d7a1755a-2c55-474d-bed4-941e6505273a.png)

`<igx-dialog message="確定要登出？" leftButtonLabel="取消" rightButtonLabel="登出" [closeOnOutsideSelect]="true" [closeOnEscape]="true" (leftButtonSelect)="dialogWindow.toggle()" #dialogWindow class="dialog-window"><igx-dialog-title>登出</igx-dialog-title></igx-dialog`
![2 screenshot-gen_code](https://user-images.githubusercontent.com/17427142/141880552-7640bb0f-f63d-4768-9319-0cbf11e4b5ac.png)

`<igx-dialog message="確定要登出？" leftButtonLabel="取消" rightButtonLabel="登出" [closeOnOutsideSelect]="true" [closeOnEscape]="true" routerLink="/login-page/login" (leftButtonSelect)="dialogWindow.toggle()" #dialogWindow class="dialog-window">
  <igx-dialog-title>登出</igx-dialog-title>
</igx-dialog>`
![3 screenshot-run_project](https://user-images.githubusercontent.com/17427142/141880557-430de05c-7cc5-42ac-8693-d8c55718d589.png)

**Comment by zdrawku** [comment]
@wnvko @Lipata it looks like the problem comes when when the "Navigate to" action is set to e child view part of another master view, for example, I've created a new master view "loginPage" with a child view "login".

![image](https://user-images.githubusercontent.com/11193764/141944487-f9fd0fdc-af48-4ec8-a792-e87bc18e70cb.png)

And then upon setting the "Navigate to" action, I've noticed that the code view panel is not showing router link input

![image](https://user-images.githubusercontent.com/11193764/141944630-a544184c-93b2-454d-a0cc-add15ab15dfc.png)

```
<igx-dialog message="Are you sure you want to do this?" leftButtonLabel="login" rightButtonLabel="close" [closeOnOutsideSelect]="true" [closeOnEscape]="true" #dialogWindow class="dialog-window">
	<igx-dialog-title>Confirmation</igx-dialog-title>
</igx-dialog>
```
If you set a "Navigate to" action to a child view part of the master view where the dialog is defined in, everything is working and generated well.

**Comment by wnvko** [comment]
This is a scenario which we are not handling now. I marked this as a bug.

**Comment by Lipata** [comment]
@jennifershih this should be fixed now.
